#ifndef IPCCODES_H
#define IPCCODES_H

#define TRAIN_SERVER_SENSOR_CB 1
#define TRAIN_SERVER_VSET_CB 2
#define TRAIN_SERVER_REVERSE_CB 3
#define TRAIN_SERVER_WHAT_VSET 4
#define TRAIN_SERVER_WHERE 5

#define CS_TICK 8
#define CS_TIME 9
#define CS_DELAY 10

#define LOCKSERVER_ACQUIRE 11
#define LOCKSERVER_RELEASE 12

#define NS_WHOIS 13
#define NS_REGISTER 14

#define CBS_REGISTER_CB 15
#define CBS_FIRE_CB 16
#define CBS_DEREGISTER 17

#define UART1_SENSOR_REPORT 18
#define UART1_MSIEN_FLIP 19
#define UART1_SHUT_DOWN 20
#define UART1_TX_READY 21
#define UART1_RX 22
#define UART1_ATOMIC_SEND 23
#define UART1_ATOMIC_NB_SEND 24

#define RES_RESERVE 25
#define RES_RELEASE 26

#define PATHS_PLANROUTE 27
#define PATHS_RELEASEPATH 28

#define UART2_TX_READY 29
#define UART2_RX 30

// shared
#define UART_GETC 31

#define PATHS_PLANROUTE_R 32

#endif
